### ISSUE TITLE
How to install ShowUI for PowerShell 7 64-bit

### ISSUE THREAD

**Issue by dburtsev** [ShowUI/ShowUI#10]
Hello

I download and unzip ShowUI.1.5. 
I copy ShowUI directory to C:\Program Files\PowerShell\7\Modules\
I execute Install-Module -Name ShowUI
I try to run ShowUI\Examples\DigitalClock.ps1

The term 'New-Label' is not recognized as the name of a cmdlet,

**Comment by fschottmann** [comment]
ShowUi runs only in PowerShell 5. I tried to fix this but the main problem is that powershell 7 runs in  .NET Core 3.1 and powershell 5.x runs in .net framework. ShowUi need for main components .net framework and mixing is not an option. 
Because of these i created my own gui generator.

**Comment by razaraz** [comment]
In theory it should be possible to support .NET 6 using MAUI, however the amount of work needed to support it is likely pretty high. It looks like there hasn't been work done in this repository in a long time, so it looks like it's up to anyone willing to take on the challenge to tackle this.
